version: '3.8'
services:
    db:
      image: 'postgres:14'
      environment:
         - POSTGRES_DB=test
         - POSTGRES_USER=postgres
         - POSTGRES_PASSWORD=Kurwa911
      ports:
         - '5432:5432'
                